config/routes.rb
RpxNowExample::Application.routes.draw do
  root :to => "users#index"
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper :all
  protect_from_forgery

  protected

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
  helper_method :current_user

  def current_user=(user)
    session[:user_id] = user.try(:id)
    @current_user = user
  end

  def access_denied
    flash[:error] = "You do not have access!"
    redirect_to :controller => :user, :action => :new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:create]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
  end

  def create
    if data = RPXNow.user_data(params[:token])
      data = {:name => data[:username], :email => data[:email], :identifier => data[:identifier]}
      self.current_user = User.find_by_identifier(data[:identifier]) || User.create!(data)
      redirect_to '/'
    else
      flash[:error] = :default
      redirect_to :action => :new
    end
  end

  def destroy
    self.current_user = nil
    redirect_to :action => :new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.erb
<%
{
  :error=>{:color=>'red', :default=>'FAIL!'},
  :notice=>{:color=>'green', :default=>'SUCCESS!'}
}.each do |k, v|
%>
  <% if flash and flash[k] %>
    <div style="color:<%=v[:color]%>">
      <% flash[k] == :default ? v[:default] : flash[k] %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_user.erb
<% if current_user %>
  Hello <%= link_to current_user, current_user %>, <%= button_to 'logout', current_user, :method=>:delete %>
<% else %>
  Hi stranger, please <%= link_to 'login!', new_user_path %>
<% end %>

app/views/layouts/application.erb
<html>
  <head>
    <title>RPX Now Example app</title>
    <%= stylesheet_link_tag 'reset', 'base' %>
  </head>
  <body>
    <div>
      <div><%= link_to 'Home', '/' %></div>
      <div><%= render 'layouts/user' %></div>
      <%= render 'layouts/flash', :locals => { :flash => flash } %>
    </div>

    <br />
    <div><%= yield %></div>
  </body>
</html>

app/views/users/index.erb
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Identifier</th>
    <th>Created</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.identifier %></td>
      <td><%= user.created_at %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.erb
<h1>Embedded</h1>
<%=raw RPXNow.embed_code('rpx-now-example', users_url) %>
<h1>Popup</h1>
<%=raw RPXNow.popup_code('open login in popup','rpx-now-example', users_url) %>

app/views/users/show.erb
Hello I am <%= @user %> and this is my page!